name: Native-AMD64

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'

      - name: Checkout master
        uses: actions/checkout@v3
        with:
          submodules: true

      #Build Image
      - name: Build Image
        run: ./gradlew bootBuildImage

      #Run an integration test to make sure the image boots
      - name: Tags the docker image to be picked up by the integration test
        run: docker image tag etiko/security-gateway:$GITHUB_REF_NAME-x86_64 etiko/security-gateway:integration-test

      - name: Run the integration test
        run: ./gradlew --console=verbose -S -i integrationTest

      - name: Remove the integration test tag
        run: docker rmi etiko/security-gateway:integration-test

      #Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #Deploy the image to the Docker registry
      - name: Push Images to Docker Registry
        run: docker push -a etiko/security-gateway

  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: create-manifest
        run: |
          docker manifest create etiko/security-gateway:$GITHUB_REF_NAME --amend etiko/security-gateway:$GITHUB_REF_NAME-x86_64
          docker manifest push etiko/security-gateway:$GITHUB_REF_NAME
          docker manifest create etiko/security-gateway:latest --amend etiko/security-gateway:$GITHUB_REF_NAME-x86_64
          docker manifest push etiko/security-gateway:latest
